baseurl = "https://jordanielder.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "pink"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Jor-Dani-Elder"
    subtitle = "Jordan is typing..."
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Jor-Dani-Elder"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "index"
        name = "RSS"
        url = "/index.xml"
      [[languages.en.menu.main]]
        identifier = "youtube"
        name = "YouTube"
        url = "https://www.youtube.com/@jmac217x/"
      [[languages.en.menu.main]]
        identifier = "mastodon"
        name = "z) Connect on Mastodon"
        url = "https://fosstodon.org/@Jordanielder"