baseurl = "https://jordanielder.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Jor-Dani-Elder"
    subtitle = "Jordan is typing..."
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    showMenuItems = "8"

    [languages.en.params.logo]
      logoText = "Jor-Dani-Elder"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "index"
        name = "RSS"
        url = "/index.xml"
      [[languages.en.menu.main]]
        identifier = "youtube"
        name = "YouTube"
        url = "https://www.youtube.com/@jmac217x/"
      [[languages.en.menu.main]]
        identifier = "mastodon"
        name = "Mastodon"
        url = "https://fosstodon.org/@Jordanielder"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/Jmac217/hugotest"
      [[languages.en.menu.main]]
        identifier = "band"
        name = "Band"
        url = "https://onallsides.rocks"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/posts/Contact"
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/jordanelder10/"
      [[languages.en.menu.main]]
        identifier = "design"
        name = "Design"
        url = "/posts/contact-jordan-elder-for-design-services"
